---
- name: restart all tomcats
  service:
    name: tomcat{{ item.value.version | default (tomcat_version) }}@{{ item.key }}
    state: restarted
  with_dict: "{{ tomcat_instances }}"

- name: restart gn-ogc-api-records
  service:
    name: gn-ogc-api-records
    state: restarted
