---
- name: Fetch the datahub archive
  get_url:
    url: "{{ datahub.url }}"
    dest: /var/www/georchestra/htdocs/datahub.zip

- name: Unzip the archive
  unarchive:
    src: /var/www/georchestra/htdocs/datahub.zip
    dest: /var/www/georchestra/htdocs/
    remote_src: true
  when: not ansible_check_mode

- name: Remove the downloaded archive
  file:
    path: /var/www/georchestra/htdocs/datahub.zip
    state: absent

- name: set base url in index.html
  replace:
    path: /var/www/georchestra/htdocs/datahub/index.html
    regexp: <base href="/">
    replace: <base href="/datahub/">

- name: add geor-header webcomponent in index.html
  blockinfile:
    path: /var/www/georchestra/htdocs/datahub/index.html
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: <body>
    block: |
      <script src='{{ georchestra.header.script | default('https://cdn.jsdelivr.net/gh/georchestra/header@dist/header.js') }}'></script>
      <geor-header
        active-app='datahub'
        {% if georchestra.header.height is defined %}height='{{ georchestra.header.height }}'{% endif %}
        {% if georchestra.header.logourl is defined %}logo-url='{{ georchestra.header.logourl }}'{% endif %}
        {% if georchestra.header.legacy is defined %}legacy-header='{{ georchestra.header.legacy }}'{% endif %}
        {% if georchestra.header.legacyurl is defined %}legacy-url='{{ georchestra.header.legacyurl }}'{% endif %}
        {% if georchestra.header.stylesheet is defined %}stylesheet='{{ georchestra.header.stylesheet }}'{% endif %}
        {% if georchestra.header.configfile is defined %}config-file='{{ georchestra.header.configfile }}'{% endif %}
      >
      </geor-header>
