---
- name: Fetch the datahub archive
  get_url:
    url: "{{ datahub.url }}"
    dest: /var/www/georchestra/htdocs/datahub.zip

- name: Unzip the archive
  unarchive:
    src: /var/www/georchestra/htdocs/datahub.zip
    dest: /var/www/georchestra/htdocs/
    remote_src: true

- name: Remove the downloaded archive
  file:
    path: /var/www/georchestra/htdocs/datahub.zip
    state: absent

- name: set base url in index.html
  replace:
    path: /var/www/georchestra/htdocs/datahub/index.html
    regexp: <base href="/">
    replace: <base href="/datahub/">
