---
- name: Install nginx
  apt:
    pkg: nginx
    state: present

- name: Check if vhost exists
  stat:
    path: /etc/nginx/sites-available/georchestra
  register: vhost_exists

- name: Template georchestra vhost
  template:
    src: vhost.j2
    dest: /etc/nginx/sites-available/georchestra
  notify: Test nginx and reload

- name: Enable georchestra vhost
  file:
    dest: /etc/nginx/sites-enabled/georchestra
    src: /etc/nginx/sites-available/georchestra
    state: link
    owner: root
    group: root
  notify: Test nginx and reload

- name: Restart nginx if vhost was deployed and we now listen  on port 443
  service:
    name: nginx
    state: restarted
  when: force_https and not vhost_exists.stat.exists

- name: Create web directories
  file:
    name: "{{ item }}"
    state: directory
  with_items:
    - /var/www/georchestra/
    - /var/www/georchestra/ssl

- name: Clone htdocs dir
  git:
    repo: https://github.com/georchestra/htdocs.git
    dest: /var/www/georchestra/htdocs/
    version: master
    accept_hostkey: true

- import_tasks: datahub.yml

- import_tasks: generate_cert.yml
  when: force_https
