- name: enable non-free and contrib for dependencies
  apt_repository: repo="deb http://ftp.fr.debian.org/debian/ wheezy main non-free contrib"

- name: install runtime dependencies
  apt: pkg={{ item }} state=installed
  with_items:
  - ttf-mscorefonts-installer
  - libjai-imageio-core-java

- name: symlink jai libs to tomcat libdir
  file: src=/usr/share/java/{{ item }}.jar dest=/usr/share/tomcat8/lib/{{ item }}.jar state=link
  with_items:
  - jai_imageio
  - jai_codec
  - mlibwrapper_jai
  - jai_core
  - clibwrapper_jiio

- name: install runtime dependencies
  apt: pkg={{ item }} state=installed
  with_items:
  - gdal-bin
  - libgdal-java

#- name: fetch libjpeg-turbo deb from sourceforge
#  get_url: dest=/tmp/ url=http://sourceforge.net/projects/libjpeg-turbo/files/1.4.0/libjpeg-turbo-official_1.4.0_amd64.deb

#- name: install libjpeg-turbo deb
#  apt: deb=/tmp/libjpeg-turbo-official_1.4.0_amd64.deb

- name: point georchestra's shared.loader to catalina.base/shared/*.jar
  lineinfile:
    dest: "{{ tomcat_basedir }}/georchestra/conf/catalina.properties"
    regexp: 'shared.loader=${catalina.home}/shared/classes,${catalina.home}/shared/*.jar,/var/lib/tomcat8/shared/classes,/var/lib/tomcat8/shared/*.jar'
    line: 'shared.loader=${catalina.home}/shared/classes,${catalina.base}/shared/*.jar,/var/lib/tomcat8/shared/classes,/var/lib/tomcat8/shared/*.jar'

- name: create tomcat shared dir
  file: dest={{ tomcat_basedir }}/georchestra/shared/ state=directory

- name: symlink gdal.jar to tomcat shared dir
  file: src=/usr/share/java/gdal.jar dest={{ tomcat_basedir }}/georchestra/shared/gdal.jar state=link

- name: hardlink gdal.jar to geoserver libdir
  file: src=/usr/share/java/gdal.jar dest={{ tomcat_basedir }}/geoserver/webapps/geoserver/WEB-INF/lib/gdal.jar state=hard

#- name: remove conflicting imageio-ext-gdal-bindings jar
#  file: path={{ tomcat_basedir }}/geoserver/webapps/geoserver/WEB-INF/lib/imageio-ext-gdal-bindings-1.9.2.jar state=absent
